import type { Match, Player, Prediction, Settlement } from "@/lib/types";
import { settleMatch } from "@/lib/settlement";

export const mockPlayers: Player[] = [
  {
    id: "p1",
    userId: "mock-user-a",
    code: "player_a",
    displayName: "贝贝",
    avatarColor: "#0f8a5f",
  },
  {
    id: "p2",
    userId: "mock-user-b",
    code: "player_b",
    displayName: "九妹",
    avatarColor: "#ff6b5f",
  },
];

export const mockMatches: Match[] = [
  {
    id: "m1",
    apiFootballFixtureId: null,
    matchNumber: 1,
    stage: "group",
    groupName: "A",
    homeTeam: "墨西哥",
    awayTeam: "南非",
    kickoffAt: "2026-06-12T03:00:00+08:00",
    venue: "墨西哥城",
    status: "scheduled",
    homeScore90: null,
    awayScore90: null,
    homeScoreExtra: null,
    awayScoreExtra: null,
    homePenaltyScore: null,
    awayPenaltyScore: null,
    winnerTeam: null,
    funQuestionKey: "both_teams_score",
    funQuestionAnswer: null,
    redCards: null,
    penaltyGoals: null,
  },
  {
    id: "m2",
    apiFootballFixtureId: null,
    matchNumber: 2,
    stage: "group",
    groupName: "B",
    homeTeam: "加拿大",
    awayTeam: "待定",
    kickoffAt: "2026-06-13T08:00:00+08:00",
    venue: "多伦多",
    status: "scheduled",
    homeScore90: null,
    awayScore90: null,
    homeScoreExtra: null,
    awayScoreExtra: null,
    homePenaltyScore: null,
    awayPenaltyScore: null,
    winnerTeam: null,
    funQuestionKey: "total_goals_3_plus",
    funQuestionAnswer: null,
    redCards: null,
    penaltyGoals: null,
  },
  {
    id: "m3",
    apiFootballFixtureId: null,
    matchNumber: 3,
    stage: "group",
    groupName: "D",
    homeTeam: "巴西",
    awayTeam: "摩洛哥",
    kickoffAt: "2026-06-15T03:00:00+08:00",
    venue: "迈阿密",
    status: "finished",
    homeScore90: 2,
    awayScore90: 1,
    homeScoreExtra: null,
    awayScoreExtra: null,
    homePenaltyScore: null,
    awayPenaltyScore: null,
    winnerTeam: "巴西",
    funQuestionKey: "both_teams_score",
    funQuestionAnswer: true,
    redCards: 0,
    penaltyGoals: 0,
  },
];

export const mockPredictions: Prediction[] = [
  {
    matchId: "m3",
    playerId: "p1",
    pickResult: "home",
    predictedHomeScore: 2,
    predictedAwayScore: 1,
    funAnswer: true,
    predictedWinnerTeam: null,
    lockedAt: "2026-06-15T02:30:00+08:00",
  },
  {
    matchId: "m3",
    playerId: "p2",
    pickResult: "home",
    predictedHomeScore: 3,
    predictedAwayScore: 1,
    funAnswer: false,
    predictedWinnerTeam: null,
    lockedAt: "2026-06-15T02:31:00+08:00",
  },
];

export const mockSettlements: Settlement[] = settleMatch(mockMatches[2], mockPredictions);
